from __future__ import annotations

from conftest import ContractCase


def _arch(
    test_id: str,
    section: str,
    capability: str,
    payload: dict,
    expected: dict,
    requirement: str,
    red: str,
) -> ContractCase:
    return ContractCase(
        test_id,
        (f"PLAN-2.0:{section}",),
        capability,
        payload,
        expected,
        requirement,
        red,
    )


REVISION_CASES = (
    _arch("ARCH-REV-001", "aggregates.Plan", "revisions:create_plan", {"plan_id": "plan-1", "initial_revision_id": "rev-1"}, {"plan_id": "plan-1", "current_revision_id": "rev-1", "stable_identity": True}, "Stable logical Plan identity with mutable current pointer only", "the stable Plan aggregate is absent"),
    _arch("ARCH-REV-002", "aggregates.PlanRevision", "revisions:approve_candidate", {"candidate": {"revision_id": "rev-2", "approval_state": "VALIDATED"}, "approver": "synthetic-user"}, {"approval_state": "APPROVED", "immutable": True}, "Approved revision is insert-once and immutable", "immutable approval semantics are absent"),
    _arch("ARCH-REV-003", "plan_revision_semantics", "revisions:build_candidate", {"plan_id": "plan-1", "parent_revision_id": "rev-1", "reason": "ADAPTATION", "manifest": {"methodology_id": "FITZGERALD_80_20_RUNNING_V1"}, "goal_snapshot": {"sport": "RUNNING", "goal_intent": "COMPLETION"}, "athlete_snapshot": {"completed_age": 40}, "parameter_snapshot": {"threshold_speed_mps": "4.00"}}, {"parent_revision_id": "rev-1", "revision_reason": "ADAPTATION", "snapshots_frozen": True, "manifest_frozen": True, "approval_state": "CANDIDATE"}, "Parent/reason/manifest/goal/athlete/parameter snapshot boundary", "complete frozen revision candidates cannot yet be built"),
    _arch("ARCH-REV-004", "content_hash", "revisions:compute_content_hash", {"revision": {"manifest": {"id": "fixture"}, "workouts": [{"date": "2026-10-01", "segments": [1, 2]}], "runtime_matches": [{"activity_id": "runtime-only"}], "ui_state": {"selected": True}}}, {"algorithm": "SHA-256", "canonical": True, "includes_prescription": True, "excludes_runtime": True, "excludes_ui_state": True}, "Canonical content identity excludes runtime/UI state", "revision content hashing and exclusion rules are absent"),
    _arch("ARCH-REV-005", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"field": "description", "kind": "SPELLING_ONLY", "prescriptive_effect": False}}, {"new_revision_required": False, "storage": "METADATA_OVERLAY"}, "Provably non-prescriptive display corrections may be overlays", "metadata-only correction classification is absent"),
    _arch("ARCH-REV-006", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"field": "duration_seconds", "before": 2400, "after": 2700}}, {"new_revision_required": True, "reason": "PRESCRIPTION_EDIT"}, "Prescriptive workout edits require new revisions", "prescriptive edit revision triggers are absent"),
    _arch("ARCH-REV-007", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"field": "methodology_id", "before": "legacy_unspecified", "after": "MAFFETONE_RUNNING_V1"}}, {"new_revision_required": True, "reason": "METHODOLOGY_CHANGE"}, "Methodology change requires a new revision", "methodology changes can not yet be prevented from mutating approved revisions"),
    _arch("ARCH-REV-008", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"field": "threshold_speed_mps", "before": "4.00", "after": "4.10"}}, {"new_revision_required": True, "reason": "ATHLETE_STATE_CHANGE"}, "Threshold change requires a new revision", "threshold changes can not yet be prevented from mutating approved revisions"),
    _arch("ARCH-REV-009", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"field": "maf_ceiling_bpm", "before": 140, "after": 145}}, {"new_revision_required": True, "reason": "ATHLETE_STATE_CHANGE"}, "MAF recalculation requires a new revision", "MAF recalculation can not yet be prevented from mutating approved revisions"),
    _arch("ARCH-REV-010", "revision_semantics.edit_rules", "revisions:classify_edit", {"edit": {"kind": "AI_REGENERATION", "prescription_changed": True}}, {"new_revision_required": True, "reason": "REGENERATION"}, "AI regeneration changing prescription requires a new revision", "AI regeneration revision triggers are absent"),
    _arch("ARCH-REV-011", "revision_semantics.runtime_outside_revision", "revisions:attach_runtime_state", {"revision_id": "rev-1", "activity_match": {"activity_id": "activity-1"}, "compliance": {"status": "VALID"}}, {"revision_content_unchanged": True, "stored_outside_revision": True}, "Runtime state separated from prescription state", "runtime observations cannot yet be attached without revision mutation"),
    _arch("ARCH-STALE-001", "revision_semantics.stale_requirements", "revision_repository:approve_revision", {"plan_id": "plan-1", "candidate_parent_revision_id": "rev-1", "expected_parent_content_hash": "hash-old", "actual_current_revision_id": "rev-2", "actual_parent_content_hash": "hash-new"}, {"committed": False, "reason": "STALE_CANDIDATE", "current_revision_id": "rev-2"}, "Guard approval by expected current parent and content identity", "stale candidates cannot yet be rejected before activation"),
)


REGISTRY_SNAPSHOT_CASES = (
    _arch("ARCH-REG-001", "methodology_registry", "registry:list_methodologies", {}, {"ids": ["FITZGERALD_80_20_RUNNING_V1", "MAFFETONE_RUNNING_V1", "legacy_unspecified"]}, "Static registry contains both V1 methods and legacy", "the methodology registry is absent"),
    _arch("ARCH-REG-002", "methodology_registry", "registry:get_methodology", {"methodology_id": "FITZGERALD_80_20_RUNNING_V1"}, {"methodology_id": "FITZGERALD_80_20_RUNNING_V1", "display_name": "80/20 Running (Fitzgerald)", "sport": "RUNNING", "version": "1", "collaborators": ["ParameterDeriver", "MethodologyPolicy", "ComplianceEvaluator"], "immutable": True}, "Versioned registry descriptor and three localized collaborators", "registry definitions and collaborator locality are absent"),
    _arch("ARCH-REG-003", "methodology_registry", "registry:get_methodology", {"methodology_id": "UNKNOWN_RUNNING_METHOD"}, {"accepted": False, "reason": "UNKNOWN_METHODOLOGY"}, "Unknown methodology rejection", "unknown methodology IDs cannot yet be rejected"),
    _arch("ARCH-REG-004", "future_methodology", "registry:register_local_definition", {"definition": {"methodology_id": "FUTURE_RUNNING_METHOD_V1", "sport": "RUNNING", "collaborators": ["FutureDeriver", "FuturePolicy", "FutureEvaluator"]}}, {"registered": True, "modified_existing_methods": False, "modified_shared_repository": False}, "Localized future-method extension without plugin framework", "localized future-method registration is absent"),
    _arch("ARCH-GOAL-001", "snapshots.goal", "snapshots:freeze_goal", {"sport": "RUNNING", "goal_intent": "COMPLETION", "event_type": "HALF_MARATHON", "event_date": "2027-03-01", "plan_start_date": "2026-10-01"}, {"sport": "RUNNING", "goal_intent": "COMPLETION", "immutable": True}, "Frozen RUNNING GoalSnapshot with required GoalIntent", "GoalSnapshot freezing is absent"),
    _arch("ARCH-GOAL-002", "snapshots.goal", "snapshots:freeze_goal", {"sport": "CYCLING", "goal_intent": "PERFORMANCE", "methodology_id": "FITZGERALD_80_20_RUNNING_V1"}, {"accepted": False, "reason": "UNSUPPORTED_SPORT_FOR_METHODOLOGY"}, "Unsupported sport cannot silently become a named V1 plan", "named-method sport validation is absent"),
    _arch("ARCH-GOAL-003", "snapshots.goal", "snapshots:compare_goal_intents", {"methodology_id": "MAFFETONE_RUNNING_V1", "intents": ["COMPLETION", "PERFORMANCE"]}, {"methodology_id_unchanged": True}, "Goal intent does not alter methodology identity", "goal-intent methodology identity invariance is absent"),
    _arch("ARCH-SNAP-001", "snapshots.athlete", "snapshots:freeze_athlete_state", {"profile": {"threshold_speed_mps": "4.00", "lthr_bpm": "170", "mutable_profile_id": "profile-1"}, "consumed_fields": ["threshold_speed_mps", "lthr_bpm"]}, {"threshold_speed_mps": "4.00", "lthr_bpm": "170", "contains_live_profile_reference": False, "immutable": True}, "Copy consumed athlete facts rather than live mutable references", "frozen consumed-fact snapshots are absent"),
    _arch("ARCH-SNAP-002", "snapshots.threshold", "snapshots:freeze_threshold", {"pace": {"evidence_class": "UNAVAILABLE"}, "lthr": {"evidence_class": "UNAVAILABLE"}}, {"named_numeric_prescription_allowed": False, "invented_targets": False}, "Unavailable thresholds cannot produce invented named numeric targets", "unavailable-threshold blocking is absent"),
    _arch("ARCH-SNAP-003", "snapshots.maffetone_parameters", "snapshots:freeze_maffetone_parameters", {"formula_version": "MAF-180-RANGE-1.0.0", "calculation_date": "2026-09-30", "completed_age": 40, "selected_adjustment": -5, "confirmed": True, "ceiling": 135, "lower_bound": 125, "provenance": "USER_SELECTED", "raw_health_answers": {"synthetic": "must-not-persist"}}, {"completed_age": 40, "ceiling": 135, "lower_bound": 125, "raw_health_answers_persisted": False, "immutable": True}, "Reproducible non-sensitive MAF parameter snapshot", "privacy-preserving MAF snapshots are absent"),
)


PRESCRIPTION_SEGMENT_CASES = (
    _arch("ARCH-RX-001", "intensity_prescription", "prescriptions:create", {"methodology_id": "FITZGERALD_80_20_RUNNING_V1", "native_target": "F80.ZONE_2", "primary": {"metric": "SPEED", "unit": "m/s", "lower": "3.04", "upper": "3.48", "lower_inclusive": True, "upper_inclusive": False}, "secondary": {"metric": "HEART_RATE", "unit": "bpm", "lower": "137.7", "upper": "153", "lower_inclusive": True, "upper_inclusive": False}, "derivation_ref": "F80-SEVEN-ZONE-1.0.0", "confidence": "HIGH", "data_quality_requirement": "VALID_PACE"}, {"valid": True, "native_target": "F80.ZONE_2", "canonical_units": True}, "Typed namespaced Fitzgerald prescription with exact bounds", "typed Fitzgerald prescriptions are absent"),
    _arch("ARCH-RX-002", "intensity_prescription", "prescriptions:create", {"methodology_id": "MAFFETONE_RUNNING_V1", "native_target": "MAF.MAF_AEROBIC_RANGE", "primary": {"metric": "HEART_RATE", "unit": "bpm", "lower": "135", "upper": "145", "lower_inclusive": True, "upper_inclusive": True}, "ceiling": {"value": "145", "inclusive": True}, "derivation_ref": "MAF-180-RANGE-1.0.0", "confidence": "HIGH", "data_quality_requirement": "VALID_HR"}, {"valid": True, "native_target": "MAF.MAF_AEROBIC_RANGE", "ceiling": {"value": "145", "inclusive": True}}, "Typed MAF prescription with explicit ceiling", "typed Maffetone prescriptions are absent"),
    _arch("ARCH-RX-003", "intensity_prescription.non_equivalence", "prescriptions:compare_semantics", {"left": "F80.ZONE_2", "right": "MAF.MAF_AEROBIC_RANGE"}, {"equivalent": False, "reason": "NAMESPACED_NATIVE_TARGETS_DIFFER"}, "Fitzgerald Zone 2 is not generic-equivalent to MAF range", "native methodology semantics are currently erased by generic-zone comparison"),
    _arch("ARCH-SEG-001", "workout_segments", "segments:expand_repeats", {"authoring": [{"kind": "WARMUP", "duration_seconds": 600}, {"repeat": 2, "children": [{"kind": "WORK", "duration_seconds": 180}, {"kind": "RECOVERY", "duration_seconds": 120}]}, {"kind": "STRIDE", "distance_metres": 100}, {"kind": "COOLDOWN", "duration_seconds": 600}, {"kind": "FREE_RUN", "load_mode": "OPEN"}, {"kind": "EVENT", "load_mode": "OPEN"}]}, {"leaf_kinds": ["WARMUP", "WORK", "RECOVERY", "WORK", "RECOVERY", "STRIDE", "COOLDOWN", "FREE_RUN", "EVENT"], "repeat_iterations": [None, 1, 1, 2, 2, None, None, None, None], "authoritative": "EXPANDED_LEAVES"}, "Deterministic one-level repeat expansion and all leaf kinds", "canonical repeat expansion is absent"),
    _arch("ARCH-SEG-002", "workout_segments.load_modes", "segments:validate_leaf", {"kind": "WORK", "load_mode": "DURATION", "duration_seconds": 300, "distance_metres": 1200, "duration_role": "AUTHORITATIVE", "distance_role": "ESTIMATED"}, {"valid": True, "authoritative_measure": "DURATION"}, "Exactly one authoritative duration/distance basis", "authoritative versus estimated load validation is absent"),
    _arch("ARCH-SEG-003", "workout_segments.both_rule", "segments:validate_leaf", {"kind": "WORK", "load_mode": "DURATION", "duration_seconds": 300, "distance_metres": 1200, "duration_role": "AUTHORITATIVE", "distance_role": "AUTHORITATIVE"}, {"valid": False, "reason": "BOTH_MEASURES_AUTHORITATIVE"}, "Secondary estimates cannot become authoritative", "dual-authoritative leaf segments cannot yet be rejected"),
    _arch("ARCH-SEG-004", "workout_segments.load_modes", "segments:validate_leaf", {"kind": "WORK", "load_mode": "DISTANCE", "distance_metres": 1000, "duration_seconds": None, "methodology_id": "FITZGERALD_80_20_RUNNING_V1", "duration_conversion": None}, {"accounting_status": "UNACCOUNTED", "invented_duration": False}, "Distance-authoritative Fitzgerald leaf needs frozen conversion", "missing duration conversion can not yet propagate as unaccounted"),
)


BOUNDARY_PERSISTENCE_CASES = (
    _arch("ARCH-AI-001", "ai_boundary", "proposal_validation:validate_ai_proposal", {"methodology_id": "MAFFETONE_RUNNING_V1", "proposal": {"family": "AEROBIC", "segments": [{"kind": "WORK", "template_ref": "MAF.AEROBIC"}], "placement": {"date": "2026-10-02"}, "description": "Original synthetic explanation"}}, {"accepted": True, "authoritative_prescriptions_rehydrated": True}, "AI may choose allowed family/structure/placement/explanation", "bounded structured AI proposal validation is absent"),
    _arch("ARCH-AI-002", "ai_boundary.forbidden_authority", "proposal_validation:validate_ai_proposal", {"methodology_id": "MAFFETONE_RUNNING_V1", "proposal": {"methodology_id_override": "FITZGERALD_80_20_RUNNING_V1", "threshold_speed_mps": "4.00", "maf_adjustment": 5, "maf_ceiling": 145, "state_transition": "HIGHER_INTENSITY_PERMITTED", "safety_override": True, "validation_outcome": "PASS", "compliance_score": 100}}, {"accepted": False, "forbidden_fields": ["methodology_id_override", "threshold_speed_mps", "maf_adjustment", "maf_ceiling", "state_transition", "safety_override", "validation_outcome", "compliance_score"]}, "AI cannot own deterministic methodology/safety/validation/compliance facts", "forbidden AI authority cannot yet be rejected as structured fields"),
    _arch("ARCH-SAFE-001", "shared_safety_policy", "validation:validate_candidate", {"methodology_findings": [{"rule": "METHOD-ALLOWS", "severity": "INFORMATIONAL"}], "safety_findings": [{"rule": "SHARED-REJECTS", "severity": "ERROR"}]}, {"accepted": False, "blocking_layer": "SHARED_SAFETY", "methodology_waiver_allowed": False, "provenance_distinct": True}, "Shared safety rejection overrides methodology allowance", "layered safety precedence is absent"),
    _arch("ARCH-COMP-001", "compliance", "compliance:describe_outputs", {"methodology_id": "FITZGERALD_80_20_RUNNING_V1"}, {"outputs": ["native_zone_time", "low_moderate_high_time", "target_adherence", "distribution_context", "coverage", "quality"], "universal_composite_score": False}, "Fitzgerald-native compliance schema", "Fitzgerald-native compliance output semantics are absent"),
    _arch("ARCH-COMP-002", "compliance", "compliance:describe_outputs", {"methodology_id": "MAFFETONE_RUNNING_V1"}, {"outputs": ["below_range_time", "in_range_time", "above_ceiling_time", "excursions", "maf_test_result_trend", "coverage", "quality"], "universal_composite_score": False}, "Maffetone-native compliance schema", "Maffetone-native compliance output semantics are absent"),
    _arch("ARCH-COMP-003", "finding_semantics.coverage", "compliance:classify_missing_data", {"observations": None, "quality": "UNAVAILABLE"}, {"status": "UNKNOWN", "quality": "UNAVAILABLE", "noncompliant": False}, "UNKNOWN/INSUFFICIENT/PARTIAL/UNAVAILABLE are not NONCOMPLIANT", "missing-data compliance semantics are absent"),
    _arch("ARCH-LEGACY-001", "legacy", "legacy:classify", {"legacy_plan_id": "legacy-plan-1"}, {"usable": True, "methodology_id": "legacy_unspecified", "fitzgerald_certified": False, "maffetone_certified": False}, "Legacy plan remains usable without retroactive certification", "legacy coexistence classification is absent"),
    _arch("ARCH-LEGACY-002", "legacy", "legacy:convert", {"legacy_plan_id": "legacy-plan-1", "selected_methodology_id": "FITZGERALD_80_20_RUNNING_V1", "goal_snapshot": {"sport": "RUNNING", "goal_intent": "COMPLETION"}}, {"created_new_revision": True, "revision_reason": "LEGACY_CONVERSION", "source_preserved": True}, "Explicit legacy conversion creates named-method revision", "lazy explicit legacy conversion is absent"),
    _arch("ARCH-ATOM-001", "atomicity", "revision_repository:approve_revision", {"candidate": {"revision_id": "rev-2", "workouts": ["workout-1"], "segments": ["segment-1"], "prescriptions": ["rx-1"], "projection": ["flat-1"]}, "current_revision_id": "rev-1", "inject_failure_at": "UPDATE_CURRENT_POINTER"}, {"committed": False, "partial_revision": False, "partial_projection": False, "current_revision_id": "rev-1"}, "Atomic approval rolls back revision/workouts/segments/Rx/projection/pointer", "transactional rollback across the revision graph is absent"),
    _arch("ARCH-ATOM-002", "atomicity", "revision_repository:approve_revision", {"candidate": {"revision_id": "rev-2", "workouts": ["workout-1"], "segments": ["segment-1"], "prescriptions": ["rx-1"], "projection": ["flat-1"]}, "current_revision_id": "rev-1", "inject_failure_at": None}, {"committed": True, "current_revision_id": "rev-2", "atomic_components": ["revision", "workouts", "segments", "prescriptions", "compatibility_projection", "active_revision_pointer"]}, "Successful approval atomically persists and activates all prescription state", "atomic revision approval is absent"),
)


ALL_ARCHITECTURE_CASES = (
    REVISION_CASES
    + REGISTRY_SNAPSHOT_CASES
    + PRESCRIPTION_SEGMENT_CASES
    + BOUNDARY_PERSISTENCE_CASES
)
