from __future__ import annotations

from conftest import ContractCase


PLAN_1_2_SHA256 = "1a82469c1c9ae5f1763cb5107091a8b3fb35c3c1a864390c77852b39bbde8523"
PLAN_2_0_SHA256 = "2ce0c6507a7be2bcb316180fbc514faf72415c7134589bd72361cdf463be00be"


def _case(
    test_id: str,
    capability: str,
    payload: dict,
    expected: dict,
    requirement: str,
    red: str,
) -> ContractCase:
    return ContractCase(test_id, (test_id,), capability, payload, expected, requirement, red)


FITZGERALD_CASES = (
    _case("F80-V1-001", "registry:validate_manifest", {"manifest": {"methodology_id": "FITZGERALD_80_20_RUNNING_V1", "methodology_version": "1", "specification_version": "1.0.0", "product_policy_version": "1.0.0", "effective_manifest_hash": "sha256:fixture"}}, {"valid": True, "immutable": True}, "Immutable full methodology manifest", "Fitzgerald revision identity cannot yet be validated or frozen"),
    _case("F80-V1-002", "fitzgerald_policy:validate_sport_scope", {"sports": ["RUNNING", "CYCLING", "STRENGTH"]}, {"RUNNING": "APPLICABLE", "CYCLING": "NOT_APPLICABLE", "STRENGTH": "NOT_APPLICABLE", "severity": "ERROR"}, "Running-only methodology scope", "non-running work cannot yet be excluded from Fitzgerald certification"),
    _case("F80-V1-003", "fitzgerald_parameters:classify_threshold", {"metric": "PACE", "value": "4.00", "unit": "m/s", "sport": "RUNNING", "method_or_protocol": "APPROVED_FIELD_TEST", "source_record": "synthetic-test-1", "measured_at": "2026-09-01", "evidence_class": "MEASURED", "quality": "VALID"}, {"evidence_class": "MEASURED", "prescription_grade": True}, "Frozen threshold evidence snapshot", "threshold provenance classes and prescription-grade gating are absent"),
    _case("F80-V1-004", "fitzgerald_parameters:derive_zones", {"threshold_speed_mps": "4.00"}, {"native_targets": ["ZONE_1", "ZONE_2", "ZONE_X", "ZONE_3", "ZONE_Y", "ZONE_4", "ZONE_5"], "ZONE_2": {"lower": "3.04", "upper": "3.48", "lower_inclusive": True, "upper_inclusive": False}}, "Seven Fitzgerald native zones from frozen threshold", "the seven-zone deterministic deriver is absent"),
    _case("F80-V1-005", "fitzgerald_policy:classify_native_targets", {"native_targets": ["ZONE_1", "ZONE_2", "ZONE_X", "ZONE_3", "ZONE_Y", "ZONE_4", "ZONE_5", "UNKNOWN"]}, {"categories": ["LOW", "LOW", "MODERATE", "MODERATE", "HIGH", "HIGH", "HIGH", "UNACCOUNTED"], "severity": "ERROR"}, "Native-zone LOW/MODERATE/HIGH mapping", "native Fitzgerald targets cannot yet be categorized without generic-zone inference"),
    _case("F80-V1-006", "fitzgerald_parameters:select_primary_metric", {"pace": {"evidence_class": "ESTIMATED", "value": "4.00"}, "lthr": {"evidence_class": "MEASURED", "value": "168"}, "context": "STEADY_AEROBIC"}, {"primary_metric": "HEART_RATE", "confidence": "REDUCED", "pace_target": None, "blocked": False}, "Pace-primary with reliable-HR fallback", "metric selection and no-invented-pace fallback are absent"),
    _case("F80-V1-007", "fitzgerald_parameters:classify_sample", {"metric": "HEART_RATE", "threshold": "170", "sample": "153.0", "display_bpm": 153}, {"native_target": "ZONE_X", "used_unrounded_value": True, "boundary_semantics": "LOWER_INCLUSIVE_UPPER_EXCLUSIVE"}, "Raw-decimal boundary and rounding semantics", "unrounded half-open native-zone classification is absent"),
    _case("F80-V1-008", "fitzgerald_policy:account_segments", {"segments": [{"kind": "WARMUP", "duration_seconds": 1200, "native_target": "ZONE_2"}, {"kind": "WORK", "duration_seconds": 1200, "native_target": "ZONE_4"}, {"kind": "COOLDOWN", "duration_seconds": 1200, "native_target": "ZONE_2"}], "workout_name": "Hard workout", "tss": 99}, {"low_seconds": 2400, "moderate_seconds": 0, "high_seconds": 1200, "accounted_seconds": 3600}, "Exact authoritative leaf-segment accounting", "structured segment-time accounting is absent"),
    _case("F80-V1-009", "fitzgerald_policy:interpret_distribution", {"low_seconds": 4794, "moderate_seconds": 0, "high_seconds": 1206, "configured_tolerance": None}, {"low_percent": "79.9", "hard_percent": "20.1", "status": "UNRATED", "severity": "INFORMATIONAL"}, "Approximate 80/20 without invented pass band", "exact distribution can not yet be reported without fabricating pass/fail"),
    _case("F80-V1-010", "fitzgerald_policy:distribution_windows", {"local_calendar_weeks": [{"week": "2026-W40", "complete": False, "low_seconds": 3600, "high_seconds": 900}], "include": ["WEEK", "ROLLING_FOUR_COMPLETED_WEEKS", "PHASE", "REVISION"]}, {"primary_window": "WEEK", "windows": ["WEEK", "ROLLING_FOUR_COMPLETED_WEEKS", "PHASE", "REVISION"], "2026-W40": {"coverage": "PARTIAL_WINDOW"}}, "Weekly primary and contextual windows", "distribution windows and partial-window semantics are absent"),
    _case("F80-V1-011", "fitzgerald_policy:validate_gap_zone_purpose", {"native_target": "ZONE_X", "purpose": "RACE_SPECIFIC", "exception": True, "exception_reason": "event-specific rehearsal", "approver": "synthetic-user"}, {"accepted": True, "category": "MODERATE", "severity": "WARNING"}, "Typed Zone X/Y purpose and exception provenance", "gap-zone purpose and race-exception validation are absent"),
    _case("F80-V1-012", "fitzgerald_policy:validate_workout_vocabulary", {"family": "AEROBIC", "description_provenance": "ORIGINAL", "segments": [{"purpose": "aerobic endurance", "native_target": "ZONE_2"}]}, {"valid": True, "official_catalog_claim": False, "severity": "ERROR"}, "Original Data Hub vocabulary with native targets", "original-vocabulary and structured-prescription validation are absent"),
    _case("F80-V1-013", "fitzgerald_policy:apply_goal_intent", {"completion": {"threshold_speed_mps": "4.00"}, "performance": {"threshold_speed_mps": "4.00"}}, {"methodology_id_unchanged": True, "zone_math_equal": True, "accounting_equal": True, "severity": "ERROR"}, "GoalIntent overlay cannot alter methodology math", "GoalIntent invariance is not enforced"),
    _case("F80-V1-014", "proposal_validation:validate_ai_proposal", {"methodology_id": "FITZGERALD_80_20_RUNNING_V1", "proposal": {"family": "HIGH_INTENSITY_INTERVALS", "segments": [{"template_ref": "F80.ZONE_4", "raw_upper_bound": "9.99"}]}}, {"accepted": False, "severity": "ERROR", "reason": "AI_NUMERIC_AUTHORITY_FORBIDDEN"}, "Bounded AI composition with deterministic rehydration", "AI-authored Fitzgerald bounds cannot yet be rejected"),
    _case("F80-V1-015", "fitzgerald_compliance:evaluate", {"prescription": {"primary_metric": "PACE", "native_target": "ZONE_2"}, "samples": [], "sensor_quality": "UNAVAILABLE"}, {"status": "UNKNOWN", "quality": "UNAVAILABLE", "composite_score": None, "severity": "INFORMATIONAL"}, "Native compliance and explicit data quality", "missing observations cannot yet produce UNKNOWN without false noncompliance"),
)


MAFFETONE_CASES = (
    _case("MAF-V1-001", "registry:validate_manifest", {"manifest": {"methodology_id": "MAFFETONE_RUNNING_V1", "methodology_version": "1", "specification_version": "1.0.0", "product_policy_version": "1.0.0", "effective_manifest_hash": "sha256:fixture"}}, {"valid": True, "immutable": True}, "Immutable full methodology manifest", "Maffetone revision identity cannot yet be validated or frozen"),
    _case("MAF-V1-002", "maffetone_policy:validate_sport_scope", {"sports": ["RUNNING", "CYCLING", "STRENGTH"]}, {"RUNNING": "APPLICABLE", "CYCLING": "NOT_APPLICABLE", "STRENGTH": "NOT_APPLICABLE", "severity": "ERROR"}, "Running-only methodology scope", "non-running work cannot yet be excluded from Maffetone certification"),
    _case("MAF-V1-003", "maffetone_parameters:derive", {"completed_age": 40, "calculation_date": "2026-09-30", "selected_adjustment": 0, "confirmed": True}, {"ceiling_bpm": 140, "lower_bpm": 130, "formula": "180-age+adjustment", "severity": "ERROR"}, "Exact MAF arithmetic from frozen inputs", "deterministic MAF formula derivation is absent"),
    _case("MAF-V1-004", "maffetone_parameters:validate_adjustment", {"selected_adjustment": -5, "confirmed": False, "provenance": "GARMIN_OBSERVATION"}, {"accepted": False, "allowed_adjustments": [-10, -5, 0, 5], "reason": "EXPLICIT_USER_CONFIRMATION_REQUIRED", "severity": "ERROR"}, "Explicit user-selected adjustment", "AI/Garmin inference and unconfirmed adjustment cannot yet be rejected"),
    _case("MAF-V1-005", "maffetone_parameters:persistable_snapshot", {"formula_version": "MAF-180-RANGE-1.0.0", "completed_age": 40, "selected_adjustment": -5, "confirmed": True, "raw_questionnaire_answers": {"medication": "synthetic-sensitive-answer", "injury": "synthetic-sensitive-answer"}}, {"selected_adjustment": -5, "confirmed": True, "contains_raw_questionnaire_answers": False, "severity": "ERROR"}, "Transient questionnaire privacy allowlist", "persisted parameter snapshots do not yet exclude raw sensitive answers"),
    _case("MAF-V1-006", "maffetone_parameters:derive", {"completed_age": 15, "calculation_date": "2026-09-30", "selected_adjustment": 0, "confirmed": True, "manual_ceiling": None}, {"blocked": True, "ceiling_bpm": None, "reason": "MANUAL_AGE_EXCEPTION_REQUIRED", "severity": "ERROR"}, "Age exception branches", "age <=16 ordinary-formula blocking is absent"),
    _case("MAF-V1-007", "maffetone_parameters:build_prescriptions", {"ceiling_bpm": 145}, {"MAF_AEROBIC_RANGE": {"lower": 135, "upper": 145, "lower_inclusive": True, "upper_inclusive": True}, "MAF_CEILING": {"ceiling": 145, "inclusive": True}, "SUB_MAF": {"upper": 135}, "severity": "ERROR"}, "Namespaced inclusive MAF range and Sub-MAF", "inclusive native MAF prescriptions are absent"),
    _case("MAF-V1-008", "maffetone_policy:validate_aerobic_base", {"state": "AEROBIC_BASE", "ceiling_bpm": 145, "segments": [{"kind": "WORK", "upper_bpm": 155}]}, {"accepted": False, "reason": "ABOVE_CEILING_PRESCRIPTION", "severity": "ERROR"}, "Aerobic-base ceiling and event separation", "above-ceiling aerobic-base prescriptions cannot yet be rejected"),
    _case("MAF-V1-009", "maffetone_policy:validate_warmup_cooldown", {"session_seconds": 4200, "segments": [{"kind": "WORK", "duration_seconds": 4200}], "exception_reason": None}, {"accepted": True, "finding": "MISSING_WARMUP_AND_COOLDOWN", "severity": "WARNING"}, "12-15 minute warmup/cooldown guideline", "typed warmup/cooldown warnings are absent"),
    _case("MAF-V1-010", "maffetone_policy:validate_maf_test", {"benchmark_identity": "MAF_TEST", "protocol_version": "MAF-GPS-30MIN-V1", "ceiling_bpm": 145, "warmup_seconds": 900, "measurement_seconds": 1800, "cooldown_seconds": 720, "hr_coverage": "VALID", "conditions": {"course": "synthetic-loop", "weather": "synthetic"}}, {"valid": True, "ordinary_run_auto_labeled": False, "severity": "ERROR"}, "Explicit MAF Test protocol identity", "MAF Test protocol and comparability validation are absent"),
    _case("MAF-V1-011", "maffetone_compliance:evaluate_test_trend", {"tests": [{"date": "2026-08-01", "pace_seconds_per_km": 360, "quality": "VALID"}, {"date": "2026-09-01", "pace_seconds_per_km": 368, "quality": "VALID", "conditions_differ": True}], "configured_tolerance": None}, {"raw_delta_seconds_per_km": 8, "status": "UNRATED", "diagnosis": None, "severity": "INFORMATIONAL"}, "Objective comparable-test trend without diagnosis", "MAF Test trend reporting without invented causality is absent"),
    _case("MAF-V1-012", "maffetone_policy:transition_state", {"current_state": "AEROBIC_BASE", "goal_intent": "PERFORMANCE", "user_confirmed": False, "evidence_reference": None, "safety_errors": []}, {"accepted": False, "state": "AEROBIC_BASE", "new_revision_required": True, "severity": "ERROR"}, "Explicit higher-intensity state gate", "goal-only automatic state transitions cannot yet be rejected"),
    _case("MAF-V1-013", "maffetone_policy:apply_goal_intent", {"completion": {"age": 40, "adjustment": 5}, "performance": {"age": 40, "adjustment": 5}}, {"methodology_id_unchanged": True, "ceiling_equal": True, "ceiling_bpm": 145, "severity": "ERROR"}, "GoalIntent cannot alter MAF formula", "GoalIntent formula and ceiling invariance is not enforced"),
    _case("MAF-V1-014", "proposal_validation:validate_ai_proposal", {"methodology_id": "MAFFETONE_RUNNING_V1", "proposal": {"family": "AEROBIC", "selected_adjustment": 5, "ceiling_bpm": 150, "state": "HIGHER_INTENSITY_PERMITTED"}}, {"accepted": False, "severity": "ERROR", "reason": "AI_METHODOLOGY_AUTHORITY_FORBIDDEN"}, "Bounded AI composition with frozen MAF state", "AI-selected adjustment, ceiling, and state cannot yet be rejected"),
    _case("MAF-V1-015", "maffetone_compliance:evaluate", {"ceiling_bpm": 145, "lower_bpm": 135, "samples": [], "hr_quality": "UNAVAILABLE"}, {"status": "UNKNOWN", "quality": "UNAVAILABLE", "below_seconds": None, "in_range_seconds": None, "above_seconds": None, "composite_score": None, "severity": "INFORMATIONAL"}, "Native MAF compliance and explicit data quality", "missing HR cannot yet produce UNKNOWN without false noncompliance"),
)


ALL_METHODOLOGY_CASES = FITZGERALD_CASES + MAFFETONE_CASES
